### ISSUE TITLE
error in clone repository 

### ISSUE THREAD

**Issue by Cocchi99** [tarxn/tiktok-ads-scrapper#1]
Hello, I can't clone the repository on my computer because it says is not public(?) can I contact someone for help? Thank you very much for you work and for your help

**Comment by tarxn** [comment]
Hey! thanks for showing intererst in my project. The repo is public. If you cannot clone the repo, you can do one of these 2 options:
1. Download as a zip
2. Fork the repo
Hope this helps!!

**Comment by Cocchi99** [comment]
Hello,
thank you for your reply! Sorry for the late response, I downloaded the
repository and it worked, I was wondering if it's possible to scrape using
account names instead of hashtags, thank you very much
Have a nice day
Costanza

**Comment by tarxn** [comment]
Hey, 
its okay! Happens to me most of the time.
we can def scrap the videos using username. You need to change the url and the html tags in the code correctly to scrap them.
If you need any help you can ping me anytime.
Cheers!!
Tarun

**Comment by tarxn** [comment]
Heyy! You can create a new issue for this task, if u have forked this project i'm more than happy to accept your pull request...... and i'm closing this one.
